version: '3.5'

services:
  cassandra_db:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./var/lib:/var/lib/cassandra

  cassandra_load_keyspace:
    image: cassandra:3.11.2
    container_name: cassandra_load_keyspace
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./db-schema/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

volumes:
  cassandra_data:
    driver: local