version: '2'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=iujt
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=iujt123
volumes:
  cassandra_data:
    driver: local